### ISSUE TITLE
Cannot log into Artifactory NPM repository

### ISSUE THREAD

**Issue by jbcpollak** [semantic-release/semantic-release#300]
I tried to use this with an artifactory repo and I got the following error message. I'm not sure, but I suspect the URL modification to add `/user/org.couchdb.user:username` is the problem

```
~/s/mfp_config_client ❯❯❯ semantic-release-cli setup
? Is the GitHub repository private? Yes
? What is your npm registry? https://mycompany.jfrog.io/mycompany/api/npm/npm-local/
? What is your npm username? username
? What is your npm email? email@mycompany.com
? What is your npm password? **********************************************************************
ERR! semantic-release Could not login to npm registry. Check your credentials.
ERR! semantic-release Error: Registry returned 500 for PUT on https://mycompany.jfrog.io/mycompany/api/npm/npm-local/-/user/org.couchdb.user:username
ERR! semantic-release     at RegClient.<anonymous> (/opt/nodes/6.2.1/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/request.js:239:14)
ERR! semantic-release     at Request._callback (/opt/nodes/6.2.1/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/request.js:170:14)
ERR! semantic-release     at Request.self.callback (/opt/nodes/6.2.1/lib/node_modules/semantic-release-cli/node_modules/request/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:106:13)
ERR! semantic-release     at Request.emit (events.js:191:7)
ERR! semantic-release     at Request.<anonymous> (/opt/nodes/6.2.1/lib/node_modules/semantic-release-cli/node_modules/request/request.js:1048:10)
ERR! semantic-release     at emitOne (events.js:96:13)
ERR! semantic-release     at Request.emit (events.js:188:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/opt/nodes/6.2.1/lib/node_modules/semantic-release-cli/node_modules/request/request.js:969:12)
ERR! semantic-release     at emitNone (events.js:91:20)
ERR! semantic-release  { Error: Registry returned 500 for PUT on https://mycompany.jfrog.io/mycompany/api/npm/npm-local/-/user/org.couchdb.user:username
ERR! semantic-release     at RegClient.<anonymous> (/opt/nodes/6.2.1/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/request.js:239:14)
ERR! semantic-release     at Request._callback (/opt/nodes/6.2.1/lib/node_modules/semantic-release-cli/node_modules/npm-registry-client/lib/request.js:170:14)
ERR! semantic-release     at Request.self.callback (/opt/nodes/6.2.1/lib/node_modules/semantic-release-cli/node_modules/request/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:106:13)
ERR! semantic-release     at Request.emit (events.js:191:7)
ERR! semantic-release     at Request.<anonymous> (/opt/nodes/6.2.1/lib/node_modules/semantic-release-cli/node_modules/request/request.js:1048:10)
ERR! semantic-release     at emitOne (events.js:96:13)
ERR! semantic-release     at Request.emit (events.js:188:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/opt/nodes/6.2.1/lib/node_modules/semantic-release-cli/node_modules/request/request.js:969:12)
ERR! semantic-release     at emitNone (events.js:91:20) pkgid: 'myproject', statusCode: 500, code: 'E500' }
```

**Comment by janppires** [comment]
I was facing the same issue.

After digging `semantic-release` code I saw two magic words: NPM_OLD_TOKEN and NPM_EMAIL.
Because `semantic-release` stills support the old way to authenticate with `npm`, people using Artifactory can use it. Simply export those two environment variables before running semantic-release command and add/create `.npmrc` file in your project, like this:

```
_auth=${NPM_OLD_TOKEN}
always-auth=true
email=${NPM_EMAIL}
```
Also export GH_TOKEN environment variable (personal access token on github settings menu). Or use the `release.githubToken` field on your `package.json` file.

I also configured `publishConfig` and `release` elements on `package.json` file:
```
"publishConfig": {
    "registry": "http://ENTERPRISE_ARTIFACTORY/api/npm/NPM_REPO_NAME/"
  },
"release": {
    "githubUrl": "https://ENTERPRISE_GH_URL",
    "githubApiPathPrefix": "api/v3",
    "verifyConditions": []
  }
```

I have done `verifyConditions:[]` just to skip the default travis behaviour. Later you can use [condition-jenkins](https://github.com/krux/condition-jenkins).

The official [jfrog website](https://www.jfrog.com/confluence/display/RTF/Npm+Registry) also provide good information about the npm registry process. Like how to get NPM Registry credentials, for NPM_OLD_TOKEN and NPM_EMAIL variables:

```
$ curl -uadmin:password "http://localhost:8081/artifactory/api/npm/auth"
```

I hope this helps other developers to take advantage of `semantic-release` tool!

Cheers

**Comment by jbcpollak** [comment]
@janppires I have tried as you suggested, but I get the following error. It is a bit different because I am also using a scoped package, but I did setup my .npmrc to use the correct scoped configuration, and we have been deploying with that config directly via `npm publish without trouble.

```
semantic-release verb pre Wrote authToken to .npmrc.
verb request uri https://mycompany.jfrog.io/mycompany/api/npm/npm-local/auth/mycompany/@scope%2Fmyproject
verb request no auth needed
info attempt registry request try #1 at 1:11:03 AM
verb request id 1aaf69ee06c4c83a
http request GET https://mycompany.jfrog.io/mycompany/api/npm/npm-local/auth/mycompany/@scope%2Fmyproject
http 401 https://mycompany.jfrog.io/mycompany/api/npm/npm-local/auth/mycompany/@scope%2Fmyproject
verb headers { date: 'Thu, 27 Apr 2017 05:11:03 GMT',
verb headers   'content-type': 'application/json;charset=ISO-8859-1',
verb headers   'content-length': '91',
verb headers   connection: 'keep-alive',
verb headers   server: 'Artifactory/5.2.1',
verb headers   'x-artifactory-id': 'aolshared2b-mycompany',
verb headers   'www-authenticate': 'Basic realm="Artifactory Realm"',
verb headers   'x-node': 'nginx-shared2b' }
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre E401 Registry returned 401 for GET on https://mycompany.jfrog.io/mycompany/api/npm/npm-local/auth/mycompany/@scope%2Fmyproject 
Error: Registry returned 401 for GET on https://mycompany.jfrog.io/mycompany/api/npm/npm-local/auth/mycompany/@scope%2Fmyproject
semantic-release ERR! pre     at makeError (/Users/me/src/myproject/node_modules/npm-registry-client/lib/request.js:304:12)
semantic-release ERR! pre     at RegClient.<anonymous> (/Users/me/src/myproject/node_modules/npm-registry-client/lib/request.js:282:14)
semantic-release ERR! pre     at Request._callback (/Users/me/src/myproject/node_modules/npm-registry-client/lib/request.js:212:14)
semantic-release ERR! pre     at Request.self.callback (/Users/me/src/myproject/node_modules/request/request.js:187:22)
semantic-release ERR! pre     at emitTwo (events.js:106:13)
semantic-release ERR! pre     at Request.emit (events.js:192:7)
semantic-release ERR! pre     at Request.<anonymous> (/Users/me/src/myproject/node_modules/request/request.js:1048:10)
semantic-release ERR! pre     at emitOne (events.js:96:13)
semantic-release ERR! pre     at Request.emit (events.js:189:7)
semantic-release ERR! pre     at IncomingMessage.<anonymous> (/Users/me/src/myproject/node_modules/request/request.js:969:12)
```

**Comment by alexw10** [comment]
We are getting the same error Failed to determine new version.
401 Registry returned 401 for get on our <artifactory dns>

Anyone have a solution?

**Comment by jbcpollak** [comment]
I also noticed that get-registry.js seems to look up the scoped registry incorrectly:

https://github.com/semantic-release/semantic-release/blob/caribou/src/lib/get-registry.js#L7

I believe this:
`var scopedRegistry = conf.get(scope + '/registry')`

should be:
`var scopedRegistry = conf.get(scope + ':registry')`

According to the npm scope documentation (https://docs.npmjs.com/misc/scope), at the bottom of the page it says:

`npm config set @myco:registry http://reg.example.com`

**Comment by alexw10** [comment]
Hmmm, well we aren't using scoped at all and still hitting this same issue.

**Comment by dalelotts** [comment]
It's not clear that the scoped URL code 100% wrong. I can set the scoped registry using `/` without error, but maybe `npm` does not validate the input. In any case, that's not the issue I am having. 

I discovered that the 401 error happens when `NPM_TOKEN` in addition to `NPM_TOKEN` and `NPM_EMAIL`. Setting _only_ `NPM_TOKEN` and `NPM_EMAIL` got @alexw10  and me past the 401 error.

**Comment by jbcpollak** [comment]
You mean setting _only_ `NPM_OLD_TOKEN`, correct? or _only_ `NPM_TOKEN`?

I don't have $NPM_TOKEN set, but I do have an _authToken set in ~/.npmrc, however its scoped only to npmjs.org:

```
$ less ~/.npmrc
//registry.npmjs.org/:_authToken=....
```

**Comment by dalelotts** [comment]
I corrected my comment. Sorry, brain doesn't work on Friday. 😭   

Semantic release writes a new .npmrc file in the project directory during the `pre` step. You can inspect that file and see what it looks like before the `npm publish` step.

**Comment by dalelotts** [comment]
Getting past the 401 error isn't the end. 👎 

Artifactory does not expose gitHead so sem-rel includes all commits in the release and the version bump is major every time if you have a breaking change in your commit history. Search past issues with `gitHead` for details

**Comment by FezVrasta** [comment]
Is there any progress on this front?

**Comment by weishang** [comment]
I tried using NPM_OLD_TOKEN and NPM_EMAIL instead, https://github.com/semantic-release/semantic-release/blob/a4951b7c3004793ef658f344e7875f4accc7e637/src/lib/publish-npm.js#L21, the generate .npmrc file looks promising, which should satisfy npm publish, but I am still getting 401 error. 

Anyone knows what to try next? At least to get rid of the 401. 

Thanks.

**Comment by pvdlg** [comment]
Authentication with Artifactory is support be `semantic-release` via the environment variables `NPM_USERNAME`, `NPM_PASSWORD`  and `NPM_EMAIL`.

I'm not sure it is support by `semantic-release-cli setup` though. Could confirm?

**Comment by pvdlg** [comment]
Duplicate of semantic-release/cli#79
